# Generated by Django 5.2.11 on 2026-02-10 21:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="appointment",
            name="customer_name",
            field=models.CharField(
                default="Cliente", help_text="Nome do cliente", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendente"),
                    ("CONFIRMED", "Confirmado"),
                    ("CANCELED", "Cancelado"),
                    ("COMPLETED", "Concluído"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
