# Generated by Django 5.2.11 on 2026-02-16 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appointments",
            "0002_appointment_created_at_appointment_customer_name_and_more",
        ),
        ("professionals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="professional",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="professionals.professional",
            ),
        ),
    ]
